name: hid
description: A multi-platform plugin which allows an application to interface with USB HID-Class devices on Linux, Windows, Android, and macOS.
version: 0.1.6
repository: https://github.com/rustui/hid/tree/main/hid
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hid_platform_interface: ^0.0.8
  hid_windows:
    path: ../hid_windows
  hid_macos:
    path: ../hid_macos
  hid_linux:
    path: ../hid_linux
  hid_android:
    path: ../hid_android


flutter:
  plugin:
      platforms:
        windows:
          default_package: hid_windows
        macos:
          default_package: hid_macos
        android:
          default_package: hid_android
        linux:
          default_package: hid_linux
